

LEVEL 2: Grundlagen des Fachwissens (14 Items)
ID: { "level": 2, "category": "Schlafphasen", "base": "Tiefschlaf", "correct": [ { "word": "Delta-Wellen", "context": "Diese langsamen Hirnwellen dominieren in der tiefsten Phase." }, { "word": "Körpererholung", "context": "Die Zellen regenerieren sich primär in diesem Zustand." } ], "distractors": [ { "word": "Beta-Wellen", "redirect": "Wachzustand", "context": "Diese Frequenzen zeigen Aktivität und Aufmerksamkeit an." }, { "word": "Powernapping", "redirect": "Kurzschlaf", "context": "Ein Nickerchen erreicht selten die tiefen Phasen." }, { "word": "Tiefkühltruhe", "redirect": "Lagerung", "context": "Kälte konserviert Lebensmittel, aber keinen Schlafzyklus." } ] },

ID: { "level": 2, "category": "Neurotransmitter", "base": "Melatonin", "correct": [ { "word": "Schlafhormon", "context": "Es steuert den Tag-Nacht-Rhythmus des Menschen." }, { "word": "Zirbeldrüse", "context": "In dieser kleinen Drüse wird es hauptsächlich produziert." } ], "distractors": [ { "word": "Adrenalin", "redirect": "Stresshormon", "context": "Dies wird bei Gefahr ausgeschüttet und macht wach." }, { "word": "Serotonin", "redirect": "Glückshormon", "context": "Es beeinflusst Stimmung und Hunger, aber nicht direkt den Schlaf." }, { "word": "Zitronensaft", "redirect": "Vitamin C", "context": "Er ist sauer und liefert keine Botenstoffe fürs Einnicken." } ] },

ID: { "level": 2, "category": "Physiologie", "base": "Circadianer Rhythmus", "correct": [ { "word": "Innere Uhr", "context": "Der biologische 24-Stunden-Zyklus des Organismus." }, { "word": "Lichtimpulse", "context": "Die Helligkeit synchronisiert diesen Taktgeber maßgeblich." } ], "distractors": [ { "word": "Mondphase", "redirect": "Aberglaube", "context": "Der Schlaf des Menschen ist nicht vom Vollmond abhängig." }, { "word": "Wochenrhythmus", "redirect": "Sieben Tage", "context": "Der biologische Takt ist deutlich kürzer." }, { "word": "Kaffee-Konsum", "redirect": "Koffeinschock", "context": "Er stört den Rhythmus, ist aber nicht seine Ursache." } ] },

ID: { "level": 2, "category": "Störungen", "base": "Insomnie", "correct": [ { "word": "Einschlafstörung", "context": "Betroffene brauchen lange, um in den Schlaf zu finden." }, { "word": "Durchschlafstörung", "context": "Das Problem ist das Wachliegen in der Nacht." } ], "distractors": [ { "word": "Hypersomnie", "redirect": "Zu viel Schlaf", "context": "Das Gegenteil: Es besteht ein übermäßiges Schlafbedürfnis." }, { "word": "Somnambulismus", "redirect": "Schlafwandeln", "context": "Dies ist eine spezifische Bewegungsstörung in der Nacht." }, { "word": "Diät-Wahn", "redirect": "Ernährung", "context": "Zu wenig Essen hält wach, ist aber keine Schlafstörung." } ] },

ID: { "level": 2, "category": "Störungen", "base": "Schlafapnoe", "correct": [ { "word": "Atemaussetzer", "context": "Die Atmung stoppt kurzzeitig im Schlaf." }, { "word": "Schnarchen", "context": "Lautes Atmen ist oft ein Begleitsymptom." } ], "distractors": [ { "word": "Hyperventilation", "redirect": "Zu schnelles Atmen", "context": "Dies ist ein überhastetes Atmen im Wachzustand." }, { "word": "Stimmverlust", "redirect": "Kehlkopf", "context": "Das hat mit der Lunge und dem Gaumen nichts zu tun." }, { "word": "Kopfkissen", "redirect": "Möbelstück", "context": "Dieses Utensil kann Symptome verstärken, ist aber nicht die Ursache." } ] },

ID: { "level": 2, "category": "Terminologie", "base": "Chronotyp", "correct": [ { "word": "Eule", "context": "Ein Mensch, der abends aktiv wird und spät schläft." }, { "word": "Lerche", "context": "Ein Mensch, der früh wach ist und früh ins Bett geht." } ], "distractors": [ { "word": "Zebra", "redirect": "Tier", "context": "Die Streifen auf der Haut haben keinen Einfluss auf den Schlaf." }, { "word": "Sternzeichen", "redirect": "Astrologie", "context": "Die biologische Veranlagung wird nicht nach Geburtstdatum festgelegt." }, { "word": "Zeitmaschine", "redirect": "Science-Fiction", "context": "Man kann die innere Uhr nicht mit Technik verstellen." } ] },

ID: { "level": 2, "category": "Neurobiologie", "base": "Adenosin", "correct": [ { "word": "Müdemacher", "context": "Dieser Botenstoff signalisiert dem Gehirn Erholungsbedarf." }, { "word": "Zellstoffwechsel", "context": "Es ist ein Nebenprodukt des Energieverbrauchs der Zellen." } ], "distractors": [ { "word": "Nikotin", "redirect": "Suchtgift", "context": "Dieses Mittel wirkt stimulierend, nicht ermüdend." }, { "word": "Tryptophan", "redirect": "Aminosäure", "context": "Dies ist die Vorstufe von Melatonin, nicht der Botenstoff selbst." }, { "word": "Koffein-Blocker", "redirect": "Chemische Reaktion", "context": "Koffein ist der Blocker, nicht das Molekül selbst." } ] },

ID: { "level": 2, "category": "Hygiene", "base": "Blaulicht", "correct": [ { "word": "Smartphone", "context": "Die Bildschirme senden dieses Licht in hohem Maße aus." }, { "word": "Melatonin-Hemmer", "context": "Die Frequenz signalisiert dem Gehirn Tageslicht." } ], "distractors": [ { "word": "Infrarot", "redirect": "Wärme", "context": "Diese Wellenlängen kann das menschliche Auge nicht sehen." }, { "word": "UV-Strahlung", "redirect": "Sonnenlicht", "context": "Diese verursacht Sonnenbrand und keine Schlafstörungen." }, { "word": "Kerzenflamme", "redirect": "Gemütlichkeit", "context": "Das Spektrum der Flamme ist orange und harmlos." } ] },

ID: { "level": 2, "category": "Schlafphasen", "base": "REM-Schlaf", "correct": [ { "word": "Rapid Eye Movement", "context": "Die Augen bewegen sich schnell unter den Lidern." }, { "word": "Traumzeit", "context": "Die meisten lebhaften Träume finden in dieser Phase statt." } ], "distractors": [ { "word": "Wachkoma", "redirect": "Pathologie", "context": "Dies ist ein schwerer neurologischer Zustand." }, { "word": "Slow Wave Sleep", "redirect": "Tiefschlaf", "context": "Dies ist die vorhergehende Phase ohne Augenbewegung." }, { "word": "Meditationszustand", "redirect": "Konzentration", "context": "Hier ist das Gehirn hochkonzentriert, nicht am Träumen." } ] },

ID: { "level": 2, "category": "Schlafstörungen", "base": "Hypersomnie", "correct": [ { "word": "Narkolepsie", "context": "Eine Form der Störung mit zwanghaften Schlafattacken." }, { "word": "Tagesschläfrigkeit", "context": "Das Hauptsymptom ist ein ständiges, übermäßiges Bedürfnis zu schlafen." } ], "distractors": [ { "word": "Insomnie", "redirect": "Schlaflosigkeit", "context": "Das Gegenteil: Hier kann man nicht schlafen." }, { "word": "Hypnose", "redirect": "Bewusstseinszustand", "context": "Dies ist eine therapeutisch herbeigeführte Trance." }, { "word": "Energieriegel", "redirect": "Ernährung", "context": "Selbst 10 Riegel helfen hier nicht langfristig." } ] },

ID: { "level": 2, "category": "Gesundheit", "base": "Schlafparalyse", "correct": [ { "word": "Wachzustand", "context": "Das Bewusstsein ist da, aber der Körper ist noch gelähmt." }, { "word": "Atonie", "context": "Der Zustand der Muskellähmung, der den Körper schützt." } ], "distractors": [ { "word": "Koma", "redirect": "Bewusstlosigkeit", "context": "Hierbei sind die Betroffenen nicht bei Bewusstsein." }, { "word": "Vollnarkose", "redirect": "Medizin", "context": "Dies wird durch Medikamente künstlich herbeigeführt." }, { "word": "Gefrierpunkt", "redirect": "Temperatur", "context": "Der Körper fühlt sich schwer an, ist aber nicht gefroren." } ] },

ID: { "level": 2, "category": "Verhalten", "base": "Koffein", "correct": [ { "word": "Adenosin-Blocker", "context": "Es besetzt die Rezeptoren, die Müdigkeit melden." }, { "word": "Stimulans", "context": "Der Stoff macht wach und beschleunigt den Puls." } ], "distractors": [ { "word": "Tryptophan", "redirect": "Aminosäure", "context": "Dies ist ein Baustein für das Schlafhormon." }, { "word": "Endorphine", "redirect": "Glückshormon", "context": "Diese Stoffe reduzieren Schmerzen, machen aber nicht wach." }, { "word": "Schlaftablette", "redirect": "Sedativum", "context": "Die Wirkung ist chemisch gesehen genau entgegengesetzt." } ] },

ID: { "level": 2, "category": "Störungen", "base": "Schlafwandeln", "correct": [ { "word": "Somnambulismus", "context": "Der medizinische Fachbegriff für dieses Phänomen." }, { "word": "Tiefschlafstörung", "context": "Es tritt meistens in der Non-REM-Phase auf." } ], "distractors": [ { "word": "Albträume", "redirect": "REM-Phase", "context": "Diese treten meistens in der Traumphase auf, nicht im Tiefschlaf." }, { "word": "Trance", "redirect": "Hypnose", "context": "Ein bewusst herbeigeführter, veränderter Zustand." }, { "word": "Geistererscheinung", "redirect": "Spuk", "context": "Wandeln ist eine medizinische Störung, kein paranormales Ereignis." } ] },

ID: { "level": 2, "category": "Kompensation", "base": "Sekundenschlaf", "correct": [ { "word": "Mikroschlaf", "context": "Der kurze, unkontrollierbare Moment des Einnickens." }, { "word": "Unfallgefahr", "context": "Im Straßenverkehr ist dies eine extreme Bedrohung." } ], "distractors": [ { "word": "Tagtraum", "redirect": "Wachzustand", "context": "Hier ist die Person wach, aber unaufmerksam." }, { "word": "Powernap", "redirect": "Kontrolliert", "context": "Dies ist ein willentlich herbeigeführter, kurzer Schlaf." }, { "word": "Amnesie", "redirect": "Gedächtnislücke", "context": "Hier fehlt die Erinnerung, der Körper ist aber wach." } ] },

ID: { "level": 2, "category": "Neurobiologie", "base": "Adenosin", "correct": [ { "word": "Müdigkeitssignal", "context": "Diese Substanz sammelt sich bei Wachheit im Gehirn an." }, { "word": "Neurotransmitter", "context": "Er vermittelt Informationen zwischen Nervenzellen." } ], "distractors": [ { "word": "Adrenalin", "redirect": "Stresshormon", "context": "Dies ist ein Wachmacher, der Adenosin entgegenwirkt." }, { "word": "Koffein", "redirect": "Blocker", "context": "Diese Droge blockiert die Rezeptoren für Adenosin." }, { "word": "Liebeskummer", "redirect": "Emotion", "context": "Emotionale Zustände sind kein physiologisches Signalmolekül." } ] },

ID: { "level": 2, "category": "Hormone", "base": "Melatonin", "correct": [ { "word": "Zirbeldrüse", "context": "Dieses kleine Organ produziert das Schlafhormon." }, { "word": "Dunkelheitshormon", "context": "Seine Produktion beginnt, wenn kein Licht mehr wahrgenommen wird." } ], "distractors": [ { "word": "Thyroxin", "redirect": "Schilddrüse", "context": "Dieses Hormon reguliert den Energiestoffwechsel, nicht den Schlaf." }, { "word": "Insulin", "redirect": "Blutzucker", "context": "Es dient der Regulation des Glukosespiegels im Körper." }, { "word": "Schlafsand", "redirect": "Märchenzutat", "context": "Es ist eine chemische Substanz, kein magisches Mineral." } ] },

ID: { "level": 2, "category": "Schlafphasen", "base": "Tiefschlaf", "correct": [ { "word": "Delta Wellen", "context": "Das EEG zeigt hier langsame, hochamplitudige Wellen." }, { "word": "Körperliche Erholung", "context": "Hier findet die Hauptregeneration des Körpers statt." } ], "distractors": [ { "word": "REM Phase", "redirect": "Träume", "context": "In dieser Phase ist das Gehirn fast so aktiv wie im Wachzustand." }, { "word": "Nickerchen", "redirect": "Kurzschlaf", "context": "Der Tiefschlaf ist Teil eines vollen Zyklus, nicht nur ein kurzer Powernap." }, { "word": "Hypnose", "redirect": "Suggestion", "context": "Dieser Zustand wird durch äußere Einflüsse herbeigeführt." } ] },

ID: { "level": 2, "category": "Störungen", "base": "Insomnie", "correct": [ { "word": "Schlaflosigkeit", "context": "Dies beschreibt die Unfähigkeit, einzuschlafen oder durchzuschlafen." }, { "word": "Wachzustand", "context": "Die Betroffenen bleiben ungewollt lange wach." } ], "distractors": [ { "word": "Somnambulismus", "redirect": "Schlafwandeln", "context": "Hierbei handelt es sich um eine Bewegungsstörung im Schlaf." }, { "word": "Narkolepsie", "redirect": "Schlafsucht", "context": "Die Betroffenen leiden unter plötzlichen Schlafattacken." }, { "word": "Dauerparty", "redirect": "Wachkultur", "context": "Die Störung ist keine bewusste Entscheidung für Aktivität." } ] },

ID: { "level": 2, "category": "Zyklus", "base": "Schlafzyklus", "correct": [ { "word": "90 Minuten", "context": "Dies ist die durchschnittliche Dauer eines vollständigen Zyklus." }, { "word": "Vier Phasen", "context": "Er besteht aus drei Non-REM Phasen und einer REM Phase." } ], "distractors": [ { "word": "24 Stunden", "redirect": "Circadian", "context": "Dies beschreibt den gesamten Tag-Nacht-Rhythmus, nicht den einzelnen Schlafabschnitt." }, { "word": "Einphase", "redirect": "Irrglaube", "context": "Der Schlaf ist ein komplexer Ablauf aus verschiedenen Phasen." }, { "word": "Waschgang", "redirect": "Textilpflege", "context": "Waschen hat zwar Zyklen, aber keine Non-REM-Stadien." } ] },

ID: { "level": 2, "category": "Ernährung", "base": "Tryptophan", "correct": [ { "word": "Aminosäure", "context": "Diese muss mit der Nahrung aufgenommen werden." }, { "word": "Serotonin-Vorstufe", "context": "Sie wird im Körper zu diesem wichtigen Glückshormon verarbeitet." } ], "distractors": [ { "word": "Koffein", "redirect": "Stimulans", "context": "Dies ist ein psychoaktiver Wirkstoff, keine Aminosäure." }, { "word": "Gluten", "redirect": "Klebereiweiß", "context": "Dies ist ein Protein in Getreide, nicht der Schlafbotenstoff." }, { "word": "Glückskeks", "redirect": "Süßspeise", "context": "Er liefert keine Aminosäuren, sondern nur Weissagungen." } ] },

ID: { "level": 2, "category": "Störungen", "base": "Schlafapnoe", "correct": [ { "word": "Atemaussetzer", "context": "Die Atmung stoppt kurzzeitig während des Schlafes." }, { "word": "Sauerstoffmangel", "context": "Dieser Zustand führt zu starker Tagesmüdigkeit." } ], "distractors": [ { "word": "Bronchitis", "redirect": "Lungenentzündung", "context": "Dies ist eine akute Infektion der Atemwege." }, { "word": "Asthma", "redirect": "Atemnot", "context": "Dies ist eine chronische Verengung der Bronchien." }, { "word": "Stiller Protest", "redirect": "Demoform", "context": "Der Betroffene leidet, protestiert aber nicht absichtlich." } ] },

ID: { "level": 2, "category": "Schlafhygiene", "base": "Blaulicht", "correct": [ { "word": "Melatoninhemmer", "context": "Es signalisiert dem Gehirn fälschlicherweise Tageslicht." }, { "word": "LED-Display", "context": "Es strahlt diese kurze Wellenlänge aus." } ], "distractors": [ { "word": "Rotlicht", "redirect": "Therapie", "context": "Diese Wellenlänge stört den Schlaf weniger." }, { "word": "Infrarot", "redirect": "Wärmestrahlen", "context": "Diese Strahlen sind für das menschliche Auge unsichtbar." }, { "word": "Blaue Stunde", "redirect": "Abendlicht", "context": "Natürliches Licht in der Dämmerung ist nicht dasselbe wie ein Handy-Display." } ] },

ID: { "level": 2, "category": "Schlafmenge", "base": "Powernap", "correct": [ { "word": "20 Minuten", "context": "Dies ist die optimale Dauer, um nicht in den Tiefschlaf zu fallen." }, { "word": "Kurzschlaf", "context": "Er dient der schnellen Wiederherstellung der Leistungsfähigkeit." } ], "distractors": [ { "word": "Vollauslastung", "redirect": "8 Stunden", "context": "Ein Powernap ist nur ein Bruchteil eines vollen Schlafzyklus." }, { "word": "Koma", "redirect": "Bewusstlosigkeit", "context": "Dies ist ein pathologischer Zustand, kein gewollter Kurzschlaf." }, { "word": "Tiefkühlung", "redirect": "Konservierung", "context": "Einfrieren verringert zwar die Aktivität, ist aber fatal." } ] },

ID: { "level": 2, "category": "Traum", "base": "Alpträume", "correct": [ { "word": "Angstzustände", "context": "Sie führen oft zu panikartigem Aufwachen." }, { "word": "REM-Schlaf", "context": "Sie treten meistens in der Phase der Traumaktivität auf." } ], "distractors": [ { "word": "Tagträume", "redirect": "Wachzustand", "context": "Diese sind bewusste Gedankengänge im wachen Zustand." }, { "word": "Visionen", "redirect": "Vorhersage", "context": "Diese werden oft als prophetisch oder religiös gedeutet." }, { "word": "Geisterstunde", "redirect": "Zeitfenster", "context": "Die Zeit an sich ist nicht verantwortlich für die schlechten Träume." } ] },

ID: { "level": 2, "category": "Paraphysiologie", "base": "Schlafparalyse", "correct": [ { "word": "Bewegungsunfähigkeit", "context": "Der Körper ist gelähmt, während der Geist erwacht." }, { "word": "Hypnagogie", "context": "Der Zustand tritt beim Einschlafen oder Aufwachen auf." } ], "distractors": [ { "word": "Krämpfe", "redirect": "Muskelzucken", "context": "Bei diesem Phänomen sind die Muskeln nicht entspannt, sondern angespannt." }, { "word": "Synkope", "redirect": "Ohnmacht", "context": "Dies ist ein kurzer Verlust des Bewusstseins durch Kreislaufprobleme." }, { "word": "Starre Pose", "redirect": "Ballett", "context": "Die Unbeweglichkeit ist nicht artistisch gewollt, sondern blockiert." } ] },

ID: { "level": 2, "category": "Verhalten", "base": "Schlafmangel", "correct": [ { "word": "Konzentrationsschwäche", "context": "Die kognitive Leistungsfähigkeit sinkt dramatisch ab." }, { "word": "Reizbarkeit", "context": "Emotional sind Betroffene oft schnell überfordert." } ], "distractors": [ { "word": "Euphorie", "redirect": "Glückszustand", "context": "Meistens löst Schlafmangel eher negative Gefühle aus." }, { "word": "Hyperaktivität", "redirect": "Überreizung", "context": "Oft führt der Mangel eher zu Trägheit und Langsamkeit." }, { "word": "Heldentat", "redirect": "Übermut", "context": "Man ist nicht heroisch, sondern nur müde und unvorsichtig." } ] },

ID: { "level": 2, "category": "Hilfsmittel", "base": "Schlafprotokoll", "correct": [ { "word": "Tagebuch", "context": "Es dient der systematischen Erfassung von Schlafgewohnheiten." }, { "word": "Diagnosehilfe", "context": "Ärzte nutzen dies zur Analyse von Störungen." } ], "distractors": [ { "word": "Uhrzeit", "redirect": "Analyseteil", "context": "Die Uhrzeit ist nur ein einzelnes Element der Aufzeichnung." }, { "word": "Lügendetektor", "redirect": "Polizei", "context": "Es soll das Schlafverhalten messen, nicht die Ehrlichkeit." }, { "word": "Kassenbon", "redirect": "Einkauf", "context": "Die Quittung über den Einkauf hat keinen Wert für die Schlafmedizin." } ] },

ID: { "level": 2, "category": "Kognition", "base": "Schlaflernen", "correct": [ { "word": "Gedächtniskonsolidierung", "context": "Informationen werden im Schlaf langfristig abgespeichert." }, { "word": "Hippocampus", "context": "Diese Gehirnregion spielt eine Schlüsselrolle bei der Speicherung." } ], "distractors": [ { "word": "Wachstudium", "redirect": "Lerntechnik", "context": "Der Hauptteil der Wissensaufnahme findet im wachen Zustand statt." }, { "word": "Vergessen", "redirect": "Zerfall", "context": "Der Schlaf soll gerade das Gegenteil, nämlich das Behalten, fördern." }, { "word": "Sprachkurs", "redirect": "Wunschdenken", "context": "Man erwirbt im Schlaf keine vollständigen neuen Fremdsprachen." } ] },


LEVEL 3: Fachwissen & Pathologie (23 Items)
ID: { "level": 3, "category": "Klassifikation", "base": "ICD-10 F51", "correct": [ { "word": "Nichtorganische Störung", "context": "Die Ursachen sind primär psychogen oder verhaltensbedingt." }, { "word": "Schlafstörungen", "context": "Dieses Kapitel umfasst Insomnie und Parasomnien." } ], "distractors": [ { "word": "ICD-10 G47", "redirect": "Neurologie", "context": "Dieser Code beschreibt rein organische Schlafstörungen wie Apnoe." }, { "word": "F32", "redirect": "Depression", "context": "Dies ist der Code für affektive Störungen, nicht primär für Schlaf." }, { "word": "Büroschlaf", "redirect": "Arbeitswelt", "context": "Eine kurze Pause am Arbeitsplatz hat keine medizinische Kodierung." } ] },

ID: { "level": 3, "category": "Neurotransmitter", "base": "Orexin", "correct": [ { "word": "Hypocretin", "context": "Es ist ein Neuropeptid zur Regulation der Wachheit." }, { "word": "Lateraler Hypothalamus", "context": "In diesem Hirareal wird der Botenstoff produziert." } ], "distractors": [ { "word": "Oxytocin", "redirect": "Bindungshormon", "context": "Dieses Hormon steuert Wehen und soziale Bindungen." }, { "word": "Insulin", "redirect": "Metabolismus", "context": "Es reguliert den Blutzuckerspiegel, nicht den Wachzustand." }, { "word": "Kaffeein", "redirect": "Schreibfehler", "context": "Der pharmakologische Stoff heißt Koffein, nicht Kaffeein." } ] },

ID: { "level": 3, "category": "Neurologie", "base": "G47.4 Narkolepsie", "correct": [ { "word": "Imperativer Schlafdrang", "context": "Betroffene schlafen tagsüber unwillkürlich ein." }, { "word": "Kataplexie", "context": "Ein plötzlicher Tonusverlust der Muskulatur bei Emotionen." } ], "distractors": [ { "word": "Insomnie", "redirect": "F51.0", "context": "Das ist das Gegenteil: Die Unfähigkeit zu schlafen." }, { "word": "Epilepsie", "redirect": "Krampfleiden", "context": "Hierbei kommt es zu pathologischen Entladungen von Neuronen." }, { "word": "Tagträumerei", "redirect": "Phantasie", "context": "Das bewusste Abschweifen ist keine neurologische Erkrankung." } ] },

ID: { "level": 3, "category": "Parasomnie", "base": "Pavor Nocturnus", "correct": [ { "word": "Nachtschreck", "context": "Ein plötzliches Aufschrecken aus dem Tiefschlaf." }, { "word": "Non-REM Störung", "context": "Das Phänomen tritt nicht während der Traumphase auf." } ], "distractors": [ { "word": "Alptraum", "redirect": "F51.5", "context": "Schlechte Träume finden fast immer im REM-Schlaf statt." }, { "word": "Schlafparalyse", "redirect": "G47.51", "context": "Hierbei ist man wach, kann sich aber nicht bewegen." }, { "word": "Geisterbahn", "redirect": "Kirmes", "context": "Der Schrecken wird hier künstlich gegen Geld erzeugt." } ] },

ID: { "level": 3, "category": "Atmung", "base": "Obstruktive Apnoe", "correct": [ { "word": "G47.3", "context": "Der ICD-Code für organische Schlafapnoe-Syndrome." }, { "word": "Rachenkollaps", "context": "Die oberen Atemwege verschließen sich durch Entspannung." } ], "distractors": [ { "word": "Zentrale Apnoe", "redirect": "Atemzentrum", "context": "Hier fehlt der Atemantrieb durch das Gehirn, der Hals ist offen." }, { "word": "Hyperventilation", "redirect": "Schnellatmung", "context": "Dies bezeichnet zu schnelles Atmen, keinen Atemstillstand." }, { "word": "Tauchsport", "redirect": "Apnoetauchen", "context": "Das bewusste Luftanhalten unter Wasser ist gewollt." } ] },

ID: { "level": 3, "category": "Diagnostik", "base": "Polysomnographie", "correct": [ { "word": "Schlaflabor", "context": "Die umfassende Messung verschiedener Körperfunktionen im Schlaf." }, { "word": "Hypnogramm", "context": "Die grafische Darstellung der Schlafstadien über die Nacht." } ], "distractors": [ { "word": "Polygraph", "redirect": "Lügendetektor", "context": "Dieses Gerät misst Stressreaktionen bei Befragungen." }, { "word": "MRT Scan", "redirect": "Radiologie", "context": "Bildgebende Verfahren zeigen die Struktur, nicht die Schlafphasen." }, { "word": "Traumdeutung", "redirect": "Psychoanalyse", "context": "Die inhaltliche Analyse von Träumen ist nicht messbar." } ] },

ID: { "level": 3, "category": "Bewegungsstörung", "base": "Restless Legs", "correct": [ { "word": "G47.6", "context": "Code für schlafbezogene Bewegungsstörungen." }, { "word": "Dopaminagonisten", "context": "Diese Medikamentengruppe lindert oft die Beschwerden." }, { "word": "Missempfindungen", "context": "Ein Kribbeln oder Ziehen in den Beinen in Ruhe." } ], "distractors": [ { "word": "Muskelkater", "redirect": "Sportfolge", "context": "Dieser Schmerz entsteht durch Mikrorisse nach Belastung." }, { "word": "Thrombose", "redirect": "Gefäßverschluss", "context": "Ein Blutgerinnsel ist ein akuter medizinischer Notfall." }, { "word": "Zappelphilipp", "redirect": "Kinderbuch", "context": "Die literarische Figur leidet eher an ADHS als an RLS." } ] },

ID: { "level": 3, "category": "Chronobiologie", "base": "Suprachiasmaticus", "correct": [ { "word": "Nucleus", "context": "Ein Kerngebiet im Hypothalamus des Gehirns." }, { "word": "Master Clock", "context": "Er steuert den zirkadianen Rhythmus des Körpers." } ], "distractors": [ { "word": "Hippocampus", "redirect": "Gedächtnis", "context": "Diese Struktur ist für das Speichern von Erinnerungen zuständig." }, { "word": "Kleinhirn", "redirect": "Motorik", "context": "Es koordiniert primär Bewegungsabläufe und Gleichgewicht." }, { "word": "Kuckucksuhr", "redirect": "Mechanik", "context": "Dieses externe Zeitmessgerät schlägt zur vollen Stunde." } ] },

ID: { "level": 3, "category": "EEG-Phänomene", "base": "Schlafspindeln", "correct": [ { "word": "Stadium N2", "context": "Diese Wellenformationen kennzeichnen den leichten Schlaf." }, { "word": "Thalamus", "context": "Sie entstehen durch Aktivität in diesem Hirnareal." } ], "distractors": [ { "word": "Alpha Wellen", "redirect": "Wachzustand", "context": "Diese Frequenz tritt bei entspannter Wachheit auf." }, { "word": "K-Komplex", "redirect": "Einzelwelle", "context": "Dies ist eine andere spezifische Wellenform im N2-Schlaf." }, { "word": "Spinnrad", "redirect": "Märchen", "context": "Dornröschen stach sich daran, aber es ist kein EEG-Muster." } ] },

ID: { "level": 3, "category": "Zahnmedizin", "base": "Bruxismus", "correct": [ { "word": "F45.8", "context": "Code für sonstige somatoforme Störungen wie Zähneknirschen." }, { "word": "Masseter", "context": "Der große Kaumuskel ist oft hypertrophiert und verspannt." } ], "distractors": [ { "word": "Karies", "redirect": "Zahnfäule", "context": "Bakterieller Befall greift den Zahnschmelz chemisch an." }, { "word": "Gingivitis", "redirect": "Entzündung", "context": "Eine Erkrankung des Zahnfleisches, nicht der Kaumuskulatur." }, { "word": "Zahnfee", "redirect": "Mythologie", "context": "Sie sammelt ausgefallene Zähne, verursacht aber kein Knirschen." } ] },

ID: { "level": 3, "category": "Therapie", "base": "CPAP", "correct": [ { "word": "Überdruckbeatmung", "context": "Die Atemwege werden durch Luftdruck offen gehalten." }, { "word": "Atemmaske", "context": "Das Gerät wird nachts auf der Nase getragen." } ], "distractors": [ { "word": "Sauerstoffbrille", "redirect": "Klinik", "context": "Dies erhöht nur die O2-Konzentration, nicht den Druck." }, { "word": "Inkubator", "redirect": "Neonatologie", "context": "Ein Brutkasten für Frühgeborene, kein Schlafgerät für Erwachsene." }, { "word": "Taucherglocke", "redirect": "Tiefsee", "context": "Ein historisches Gerät, um unter Wasser atmen zu können." } ] },

ID: { "level": 3, "category": "Schlafphasen", "base": "REM Atonie", "correct": [ { "word": "Muskellähmung", "context": "Verhindert das physische Ausagieren von Träumen." }, { "word": "Schutzmechanismus", "context": "Die Motorik wird vom Hirnstamm aktiv blockiert." } ], "distractors": [ { "word": "Rigor", "redirect": "Parkinson", "context": "Eine pathologische Muskelsteifigkeit bei Bewegung." }, { "word": "Spasmus", "redirect": "Krampf", "context": "Eine schmerzhafte, unwillkürliche Muskelanspannung." }, { "word": "Faulheit", "redirect": "Charakter", "context": "Mangelnde Bewegungsmotivation ist keine physiologische Atonie." } ] },

ID: { "level": 3, "category": "Pharmakologie", "base": "Z-Substanzen", "correct": [ { "word": "Zolpidem", "context": "Ein häufig verschriebenes kurz wirksames Hypnotikum." }, { "word": "GABA Rezeptor", "context": "Die Wirkstoffe binden an diesen inhibitorischen Komplex." } ], "distractors": [ { "word": "Benzodiazepine", "redirect": "Tranquilizer", "context": "Chemisch anders aufgebaut, auch wenn sie ähnlich wirken." }, { "word": "Antibiotika", "redirect": "Infektion", "context": "Wirken gegen Bakterien, nicht schlafanstoßend." }, { "word": "Z-Promi", "redirect": "Boulevard", "context": "Personen öffentlichen Interesses haben keine pharmakologische Wirkung." } ] },

ID: { "level": 3, "category": "Rhythmik", "base": "Jetlag", "correct": [ { "word": "Desynchronisation", "context": "Innere Uhr und Außenzeit passen nicht mehr zusammen." }, { "word": "G47.2", "context": "ICD-Code für Störungen des Schlaf-Wach-Rhythmus." } ], "distractors": [ { "word": "Kinetose", "redirect": "Reisekrankheit", "context": "Übelkeit durch Bewegung, unabhängig von der Zeitzone." }, { "word": "Heimweh", "redirect": "Emotion", "context": "Ein psychisches Gefühl des Vermissens, kein Rhythmusproblem." }, { "word": "Turbulenz", "redirect": "Luftfahrt", "context": "Wackelnde Flugzeuge stören den Schlaf, sind aber kein Syndrom." } ] },

ID: { "level": 3, "category": "Parasomnie", "base": "Somniloquie", "correct": [ { "word": "Sprechen im Schlaf", "context": "Vokalisierung ohne Bewusstsein während der Nacht." }, { "word": "F51.3", "context": "Fällt unter sonstige Parasomnien im ICD-10." } ], "distractors": [ { "word": "Logorrhoe", "redirect": "Redefluss", "context": "Krankhafter Zwang zum vielen Reden im Wachzustand." }, { "word": "Aphasie", "redirect": "Sprachstörung", "context": "Verlust des Sprechvermögens nach Hirnschädigung." }, { "word": "Selbstgespräch", "redirect": "Monolog", "context": "Bewusstes Reden mit sich selbst zur Gedankenordnung." } ] },

ID: { "level": 3, "category": "Neurologie", "base": "RBD", "correct": [ { "word": "REM Verhaltensstörung", "context": "Die physiologische Muskelatonie im Traumschlaf fehlt." }, { "word": "Synukleopathie", "context": "Oft ein Frühsymptom für Parkinson oder Demenz." } ], "distractors": [ { "word": "Schlafwandeln", "redirect": "Non-REM", "context": "Dies passiert im Tiefschlaf, nicht in der Traumphase." }, { "word": "Restless Legs", "redirect": "G47.6", "context": "Ein Bewegungsdrang in Ruhe, aber bei vollem Bewusstsein." }, { "word": "RGB", "redirect": "Farbraum", "context": "Rot-Grün-Blau ist ein Farbmodell für Monitore." } ] },

ID: { "level": 3, "category": "Hormone", "base": "Cortisol", "correct": [ { "word": "Glukokortikoid", "context": "Ein Stresshormon aus der Nebennierenrinde." }, { "word": "Aufwachsignal", "context": "Der Spiegel steigt morgens stark an, um Energie bereitzustellen." } ], "distractors": [ { "word": "Melatonin", "redirect": "Schlafhormon", "context": "Dies ist der Gegenspieler, der den Körper herunterfährt." }, { "word": "Testosteron", "redirect": "Androgen", "context": "Sexualhormon, das nicht primär den Tagesrhythmus steuert." }, { "word": "Cortado", "redirect": "Espresso", "context": "Ein spanisches Kaffeegetränk mit etwas Milch." } ] },

ID: { "level": 3, "category": "Arbeitsmedizin", "base": "Schichtarbeitersyndrom", "correct": [ { "word": "SWSD", "context": "Shift Work Sleep Disorder durch rotierende Arbeitszeiten." }, { "word": "Chronodispersion", "context": "Störung der biologischen Rhythmen durch Nachtarbeit." } ], "distractors": [ { "word": "Burnout", "redirect": "Z73.0", "context": "Ein Zustand emotionaler Erschöpfung, nicht zwingend durch Schichten." }, { "word": "Boreout", "redirect": "Unterforderung", "context": "Psychische Belastung durch Langeweile am Arbeitsplatz." }, { "word": "Montagsblues", "redirect": "Wochenstart", "context": "Motivationsmangel zum Wochenbeginn ist keine Krankheit." } ] },

ID: { "level": 3, "category": "Psychologie", "base": "Psychophysiologische Insomnie", "correct": [ { "word": "Erlernte Schlaflosigkeit", "context": "Das Bett selbst wird zum Auslöser für Anspannung." }, { "word": "Konditionierung", "context": "Der Körper verbindet das Schlafzimmer mit Wachsein." } ], "distractors": [ { "word": "Idiopathische Insomnie", "redirect": "Kindheit", "context": "Diese Form besteht lebenslang ohne erkennbare Ursache." }, { "word": "Paradoxe Insomnie", "redirect": "Fehlwahrnehmung", "context": "Man schläft objektiv, fühlt sich aber subjektiv wach." }, { "word": "Prüfungsangst", "redirect": "Situativ", "context": "Diese Angst ist auf ein Ereignis bezogen, nicht auf den Schlaf." } ] },

ID: { "level": 3, "category": "Diagnostik", "base": "MSLT", "correct": [ { "word": "Multipler Schlaflatenztest", "context": "Misst die Einschlafneigung tagsüber im Schlaflabor." }, { "word": "Narkolepsie-Diagnose", "context": "Ein verfrühtes Auftreten von REM-Schlaf ist pathologisch." } ], "distractors": [ { "word": "MWST", "redirect": "Steuer", "context": "Die Mehrwertsteuer wird vom Finanzamt erhoben." }, { "word": "IQ-Test", "redirect": "Intelligenz", "context": "Misst kognitive Fähigkeiten, nicht die Müdigkeit." }, { "word": "EKG", "redirect": "Herz", "context": "Zeichnet die Herzströme auf, nicht die Schlaflatenz." } ] },

ID: { "level": 3, "category": "Symptom", "base": "Hypnagogie", "correct": [ { "word": "Einschlafstadium", "context": "Der Übergangszustand vom Wachsein zum Schlaf." }, { "word": "Halluzinationen", "context": "Oft treten visuelle oder akustische Sinnestäuschungen auf." } ], "distractors": [ { "word": "Hypnopompie", "redirect": "Aufwachen", "context": "Dies bezeichnet den umgekehrten Zustand beim Erwachen." }, { "word": "Hypnose", "redirect": "Trance", "context": "Ein künstlich herbeigeführter Zustand der Suggestibilität." }, { "word": "Agonie", "redirect": "Sterbephase", "context": "Der Todeskampf hat nichts mit normalem Einschlafen zu tun." } ] },

ID: { "level": 3, "category": "Atmung", "base": "Cheyne Stokes", "correct": [ { "word": "Periodische Atmung", "context": "Atemzüge werden flacher, setzen aus und werden wieder tiefer." }, { "word": "Herzinsuffizienz", "context": "Diese Atemform tritt oft bei schwerer Herzschwäche auf." } ], "distractors": [ { "word": "Schnappatmung", "redirect": "Terminal", "context": "Irreguläre Atemzüge kurz vor dem Tod." }, { "word": "Kussmaul-Atmung", "redirect": "Azidose", "context": "Tiefe Atmung bei Übersäuerung des Blutes (Diabetes)." }, { "word": "Stokes", "redirect": "Physik", "context": "Ein Gesetz der Strömungslehre, keine Atmungsform." } ] },

ID: { "level": 3, "category": "Verkehrsmedizin", "base": "Sekundenschlaf", "correct": [ { "word": "Mikroschlaf", "context": "Ungewolltes Einnicken für wenige Sekunden." }, { "word": "Monotonieintoleranz", "context": "Tritt oft bei langweiligen Strecken auf der Autobahn auf." } ], "distractors": [ { "word": "Mittagsschlaf", "redirect": "Siesta", "context": "Eine geplante Erholungspause, kein gefährliches Einnicken." }, { "word": "Ohnmacht", "redirect": "Kreislauf", "context": "Ein medizinischer Kollaps, nicht durch Schläfrigkeit bedingt." }, { "word": "Blinzeln", "redirect": "Lidschlag", "context": "Befeuchtet das Auge und dauert nur Millisekunden." } ] },
 

LEVEL 4: Expertenniveau (Neurophysiologie & Pathophysiologie)
ID: { "level": 4, "category": "Neuroanatomie", "base": "VLPO", "correct": [ { "word": "Schlafschalter", "context": "Der ventrolaterale präoptische Nukleus initiiert den Schlaf." }, { "word": "GABAerg", "context": "Die Neuronen nutzen GABA und Galanin zur Hemmung." } ], "distractors": [ { "word": "Locus Coeruleus", "redirect": "Noradrenalin", "context": "Dieser Kern fördert Wachheit und Aufmerksamkeit." }, { "word": "Raphe Kerne", "redirect": "Serotonin", "context": "Diese Strukturen sind eher im Wachzustand aktiv." }, { "word": "Amygdala", "redirect": "Emotion", "context": "Das Angstzentrum ist nicht der primäre on/off-Schalter." } ] },

ID: { "level": 4, "category": "Genetik", "base": "FFI", "correct": [ { "word": "Prionenerkrankung", "context": "Verursacht durch falsch gefaltete Proteine im Gehirn." }, { "word": "Thalamusatrophie", "context": "Der selektive Zelltod im Thalamus verhindert Schlaf." } ], "distractors": [ { "word": "Alzheimer", "redirect": "Beta-Amyloid", "context": "Eine kortikale Demenz, primär Gedächtnisverlust." }, { "word": "Chorea Huntington", "redirect": "Bewegungsstörung", "context": "Genetisch bedingt, aber primär motorisch und kognitiv." }, { "word": "Parkinson", "redirect": "Substantia Nigra", "context": "Dopaminmangel führt zu Rigor und Tremor." } ] },

ID: { "level": 4, "category": "Molekularbiologie", "base": "Clock Gene", "correct": [ { "word": "BMAL1", "context": "Ein Transkriptionsfaktor, der den zirkadianen Rhythmus steuert." }, { "word": "PER2", "context": "Ein Period-Gen, dessen Expression oszilliert." } ], "distractors": [ { "word": "BRCA1", "redirect": "Onkologie", "context": "Ein Tumorsuppressor-Gen, assoziiert mit Brustkrebs." }, { "word": "HOX Gene", "redirect": "Embryologie", "context": "Diese Gene steuern den Körperbauplan in der Entwicklung." }, { "word": "CRISPR", "redirect": "Genschere", "context": "Eine Methode zur Editierung, kein körpereigenes Gen." } ] },

ID: { "level": 4, "category": "Signalweg", "base": "Retinohypothalamischer Trakt", "correct": [ { "word": "Melanopsin", "context": "Das Photopigment in den Ganglienzellen der Netzhaut." }, { "word": "Lichtsynchronisation", "context": "Leitet Helligkeitsinformation direkt zum SCN." } ], "distractors": [ { "word": "Tractus Opticus", "redirect": "Visueller Kortex", "context": "Leitet Bildinformationen zum Sehen, nicht zur Uhr." }, { "word": "Zapfen", "redirect": "Farbsehen", "context": "Photorezeptoren für das photopische Sehen am Tag." }, { "word": "Stäbchen", "redirect": "Skotopisches Sehen", "context": "Zuständig für das Sehen bei geringer Helligkeit." } ] },

ID: { "level": 4, "category": "Regulation", "base": "Zwei-Prozess-Modell", "correct": [ { "word": "Prozess S", "context": "Der homöostatische Schlafdruck steigt mit der Wachdauer." }, { "word": "Prozess C", "context": "Der zirkadiane Rhythmus moduliert die Schlafbereitschaft." } ], "distractors": [ { "word": "Prozess T", "redirect": "Thermodynamik", "context": "Temperatur ist ein Marker, kein definierter Prozessname." }, { "word": "REM-Druck", "redirect": "Traumschlaf", "context": "Dies ist spezifisch für eine Phase, nicht das Gesamtmodell." }, { "word": "Lustprinzip", "redirect": "Psychoanalyse", "context": "Freuds Konzept passt nicht in die Borbély-Kurve." } ] },

ID: { "level": 4, "category": "Physiologie", "base": "Glymphatisches System", "correct": [ { "word": "Liquorfluss", "context": "Spült metabolische Abfallprodukte aus dem Interstitium." }, { "word": "Astrozyten", "context": "Aquaporin-4-Kanäle spielen hierbei eine Schlüsselrolle." } ], "distractors": [ { "word": "Lymphsystem", "redirect": "Immunologie", "context": "Das Gehirn besitzt keine klassischen Lymphgefäße." }, { "word": "Blut-Hirn-Schranke", "redirect": "Barriere", "context": "Sie schützt das Gehirn, reinigt es aber nicht aktiv." }, { "word": "Dialyse", "redirect": "Nephrologie", "context": "Ein technisches Verfahren zur Blutreinigung bei Nierenversagen." } ] },

ID: { "level": 4, "category": "Rezeptorpharmakologie", "base": "GABA-A Rezeptor", "correct": [ { "word": "Chloridkanal", "context": "Öffnung führt zum Einstrom negativ geladener Ionen." }, { "word": "Hyperpolarisation", "context": "Das Membranpotenzial sinkt, die Erregbarkeit nimmt ab." } ], "distractors": [ { "word": "Natriumkanal", "redirect": "Depolarisation", "context": "Dies würde die Nervenzelle aktivieren statt hemmen." }, { "word": "G-Protein", "redirect": "Metabotrop", "context": "GABA-B Rezeptoren nutzen diesen langsameren Weg." }, { "word": "NMDA Rezeptor", "redirect": "Glutamat", "context": "Dieser Rezeptor wirkt exzitatorisch, also anregend." } ] },

ID: { "level": 4, "category": "Schlafmedizin", "base": "Kleine-Levin-Syndrom", "correct": [ { "word": "Hypersomnie", "context": "Periodisch auftretende Phasen extremen Schlafbedürfnisses." }, { "word": "Hyperphagie", "context": "Begleitet von übermäßigem Essverhalten im Wachzustand." } ], "distractors": [ { "word": "Insomnie", "redirect": "Schlaflosigkeit", "context": "Das genaue Gegenteil der Symptomatik dieses Syndroms." }, { "word": "Narkolepsie", "redirect": "G47.4", "context": "Hier sind die Schlafattacken kurz und täglich, nicht phasenweise." }, { "word": "Winterschlaf", "redirect": "Hibernation", "context": "Ein physiologischer Zustand bei Tieren, keine menschliche Pathologie." } ] },

ID: { "level": 4, "category": "Neurochemie", "base": "REM-On Neuronen", "correct": [ { "word": "Acetylcholin", "context": "Cholinerge Neuronen im Hirnstamm triggern den REM-Schlaf." }, { "word": "Pons", "context": "Die Brücke ist das anatomische Zentrum der Generierung." } ], "distractors": [ { "word": "Noradrenalin", "redirect": "REM-Off", "context": "Dieser Transmitter unterdrückt den REM-Schlaf aktiv." }, { "word": "Serotonin", "redirect": "Raphe", "context": "Auch 5-HT wirkt hemmend auf die Traumphasen." }, { "word": "Frontallappen", "redirect": "Exekutive", "context": "Dieser Bereich ist im REM-Schlaf weitgehend inaktiviert." } ] },

ID: { "level": 4, "category": "Parasomnie", "base": "REM-Verhaltensstörung", "correct": [ { "word": "Alpha-Synuclein", "context": "Ablagerungen dieses Proteins schädigen Hirnstammkerne." }, { "word": "Prodromalmarker", "context": "Häufig Vorbote für Morbus Parkinson oder Lewy-Körper-Demenz." } ], "distractors": [ { "word": "Tau-Protein", "redirect": "Alzheimer", "context": "Ein anderes Protein, assoziiert mit neurofibrillären Bündeln." }, { "word": "Somnambulismus", "redirect": "Slow Wave Sleep", "context": "Schlafwandeln passiert im Tiefschlaf, nicht im REM." }, { "word": "Veitstanz", "redirect": "Chorea", "context": "Eine historische Bezeichnung für hyperkinetische Bewegungsstörungen." } ] },

ID: { "level": 4, "category": "Diagnostik", "base": "HLA-DQB1*0602", "correct": [ { "word": "Narkolepsie Typ 1", "context": "Starke genetische Assoziation mit Hypocretin-Mangel." }, { "word": "Allel", "context": "Ein spezifischer Genort im Haupthistokompatibilitätskomplex." } ], "distractors": [ { "word": "Trisomie 21", "redirect": "Chromosom", "context": "Eine numerische Chromosomenaberration, kein Allel." }, { "word": "BRCA2", "redirect": "Krebsrisiko", "context": "Genetischer Marker für Mammakarzinome." }, { "word": "Blutgruppe A", "redirect": "Hämatologie", "context": "Oberflächenantigene auf Erythrozyten, keine HLA-Typisierung." } ] },

ID: { "level": 4, "category": "Elektrophysiologie", "base": "K-Komplex", "correct": [ { "word": "Biphasisch", "context": "Hohe negative Amplitude gefolgt von positiver Welle." }, { "word": "Schlafschutz", "context": "Unterdrückt kortikale Reaktionen auf äußere Reize." } ], "distractors": [ { "word": "Schlafspindel", "redirect": "12-14 Hz", "context": "Ein oszillierendes Muster, keine einzelne große Welle." }, { "word": "Sawtooth Waves", "redirect": "REM-Schlaf", "context": "Sägezahnwellen treten in der Traumphase auf." }, { "word": "QRS-Komplex", "redirect": "Kardiologie", "context": "Dieser Zacken gehört ins EKG, nicht ins EEG." } ] },

ID: { "level": 4, "category": "Pharmakokinetik", "base": "Halbwertszeit", "correct": [ { "word": "Elimination", "context": "Zeitspanne, in der die Plasmakonzentration um 50% sinkt." }, { "word": "Kumulation", "context": "Bei langer Dauer droht Hangover am nächsten Tag." } ], "distractors": [ { "word": "Bioverfügbarkeit", "redirect": "Absorption", "context": "Anteil des Wirkstoffs, der im System ankommt." }, { "word": "Placeboeffekt", "redirect": "Psychologie", "context": "Wirkung ohne pharmakologische Substanz." }, { "word": "Verfallsdatum", "redirect": "Lagerung", "context": "Der Zeitpunkt, ab dem das Medikament nicht mehr genutzt werden sollte." } ] },

ID: { "level": 4, "category": "Neurologie", "base": "Non-24", "correct": [ { "word": "Freilaufender Rhythmus", "context": "Die innere Uhr synchronisiert sich nicht mit dem 24h-Tag." }, { "word": "Blindheit", "context": "Häufig betroffen, da der Licht-Zeitgeber fehlt." } ], "distractors": [ { "word": "Schichtarbeit", "redirect": "Exogen", "context": "Hier wird der Rhythmus von außen gestört, nicht von innen." }, { "word": "Jetlag", "redirect": "Transatlantik", "context": "Eine temporäre Verschiebung, keine chronische Entkopplung." }, { "word": "25. Stunde", "redirect": "Film", "context": "Ein cineastisches Werk, kein chronobiologisches Syndrom." } ] },

ID: { "level": 4, "category": "Schlafarchitektur", "base": "Rebound-Effekt", "correct": [ { "word": "Kompensation", "context": "Der Körper holt entzogenen REM- oder Tiefschlaf nach." }, { "word": "Intensivierung", "context": "Die Phasen treten schneller und dichter auf als normal." } ], "distractors": [ { "word": "Toleranz", "redirect": "Gewöhnung", "context": "Die Wirkung einer Substanz lässt bei Dauergebrauch nach." }, { "word": "Entzugssyndrom", "redirect": "Abhängigkeit", "context": "Körperliche Symptome beim Absetzen einer Droge." }, { "word": "Bumerang", "redirect": "Spielzeug", "context": "Kehrt physikalisch zurück, physiologisch aber irrelevant." } ] },

ID: { "level": 4, "category": "Pharmakologie", "base": "Melatonin-Agonisten", "correct": [ { "word": "Ramelteon", "context": "Bindet selektiv an MT1 und MT2 Rezeptoren." }, { "word": "Zirkadiane Wirkung", "context": "Verschiebt die Schlafphase ohne klassische Sedierung." } ], "distractors": [ { "word": "Benzodiazepin", "redirect": "GABA-A", "context": "Wirkt über Chloridkanäle angstlösend und muskelrelaxierend." }, { "word": "Antihistaminika", "redirect": "H1-Blocker", "context": "Alte Allergiemittel machen müde als Nebenwirkung." }, { "word": "Baldrian", "redirect": "Phytotherapie", "context": "Ein pflanzliches Extrakt mit unklarem Rezeptormechanismus." } ] },

⸻